Fixes for instalation prereqs
  * curl and zenity are now mentioned as prereqs in README
  * locate is only used if installed
  * install checks for zenity

Fixes issue #1

diff --git a/seafile-share-link b/seafile-share-link
--- a/seafile-share-link
+++ b/seafile-share-link
@@ -1,16 +1,23 @@
 #!/bin/bash
 
+# This script was created in an afternoon. It is a hack, but may be useful until
+# Nautilus (and command line) support becomes part of the Seafile client itself
+#
+# Anders Bandholm, july 2015
+
 
 if [ -d ~/Seafile/.seafile-data ]
 then
     SEAFILE_CONF=~/Seafile/.seafile-data
-else
+elif [ `which locate` ]
+then
+    # if not in default place, search with locate (if locate is available)
     SEAFILE_CONF=$(locate /*/.seafile-data)
-    if [ -z "$SEAFILE_CONF" ] || [ ! -d "$SEAFILE_CONF" ]
-    then
-	echo "Error: Could not find Seafile configuration" >&2
-	exit 2
-    fi
+fi
+if [ -z "$SEAFILE_CONF" ] || [ ! -d "$SEAFILE_CONF" ]
+then
+    echo "Error: Could not find Seafile configuration" >&2
+    exit 2
 fi
 
 function sql_lookup {
@@ -39,7 +46,7 @@ DIR_NAME=`dirname "$CANON"`
 ACCOUNT_INFO=$(
     sql_lookup "$SEAFILE_CONF/repo.db" "select repo_id, value from RepoProperty where key='worktree';" |
 	while
-	    read repo folder 
+	    read repo folder
 	do
 	    if [[ "$DIR_NAME" =~ ^$folder ]]
 	    then
